name: Fetch Server Logs
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  fetch-logs:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and get logs
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "==== /opt/app/ Contents ===="
            ls -la /opt/app/
            echo "==== EXTERNAL APPLICATION.PROPERTIES ===="
            sudo cat /opt/app/application* || echo "None found"
            echo "========================================="
